-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 09:06:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sharing_Books
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sharing_Books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sharing_Books` DEFAULT CHARACTER SET utf8 ;
USE `Sharing_Books` ;

-- -----------------------------------------------------
-- Table `Sharing_Books`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sharing_Books`.`domicilio` (
  `ID_domicilio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(70) NOT NULL,
  `altura` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(70) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_domicilio`),
  UNIQUE INDEX `ID_domicilio_UNIQUE` (`ID_domicilio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sharing_Books`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sharing_Books`.`usuario` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `telefono` VARCHAR(45) NULL,
  `e_mail` VARCHAR(70) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `domicilio_ID_domicilio` INT NOT NULL,
  PRIMARY KEY (`ID_usuario`, `domicilio_ID_domicilio`),
  UNIQUE INDEX `ID_usuario_UNIQUE` (`ID_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `fk_usuario_domicilio1_idx` (`domicilio_ID_domicilio` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_domicilio1`
    FOREIGN KEY (`domicilio_ID_domicilio`)
    REFERENCES `Sharing_Books`.`domicilio` (`ID_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sharing_Books`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sharing_Books`.`libro` (
  `ID_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(70) NULL,
  `editorial` VARCHAR(50) NULL,
  `fecha_publicacion` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `usuario_ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_libro`, `usuario_ID_usuario`),
  UNIQUE INDEX `ID_libro_UNIQUE` (`ID_libro` ASC) VISIBLE,
  INDEX `fk_libro_usuario_idx` (`usuario_ID_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_libro_usuario`
    FOREIGN KEY (`usuario_ID_usuario`)
    REFERENCES `Sharing_Books`.`usuario` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sharing_Books`.`intercambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sharing_Books`.`intercambio` (
  `ID_intercambio` INT NOT NULL AUTO_INCREMENT,
  `fecha_intercambio` DATE NULL,
  `domicilio_ID_domicilio` INT NOT NULL,
  PRIMARY KEY (`ID_intercambio`, `domicilio_ID_domicilio`),
  UNIQUE INDEX `ID_intercambio_UNIQUE` (`ID_intercambio` ASC) VISIBLE,
  INDEX `fk_intercambio_domicilio1_idx` (`domicilio_ID_domicilio` ASC) VISIBLE,
  CONSTRAINT `fk_intercambio_domicilio1`
    FOREIGN KEY (`domicilio_ID_domicilio`)
    REFERENCES `Sharing_Books`.`domicilio` (`ID_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sharing_Books`.`usuario_intercambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sharing_Books`.`usuario_intercambio` (
  `ID_usuario` INT NOT NULL,
  `ID_intercambio` INT NOT NULL,
  PRIMARY KEY (`ID_usuario`, `ID_intercambio`),
  CONSTRAINT `ID_usuario`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `Sharing_Books`.`usuario` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_intercambio`
    FOREIGN KEY ()
    REFERENCES `Sharing_Books`.`intercambio` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sharing_Books`.`libro_intercambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sharing_Books`.`libro_intercambio` (
  `ID_libro` INT NOT NULL,
  `ID_intercambio` INT NOT NULL,
  PRIMARY KEY (`ID_libro`, `ID_intercambio`),
  CONSTRAINT `ID_libro`
    FOREIGN KEY ()
    REFERENCES `Sharing_Books`.`libro` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_intercambio`
    FOREIGN KEY ()
    REFERENCES `Sharing_Books`.`intercambio` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
